### ISSUE TITLE
Algorithm should be also specified when decoding

### ISSUE THREAD

**Issue by graywolf** [nickdufresne/jwt-sinatra-example#1]
Based on https://github.com/jwt/ruby-jwt readme I believe that https://github.com/nickdufresne/jwt-sinatra-example/blob/4e7cd15a45e6fa26f95265a27bb7d616638967e4/app.rb#L75 should also specify the algorithm to use. Setting it only in `encode` is not sufficient.

More info:

https://github.com/jwt/ruby-jwt#algorithms-and-usage

https://www.reddit.com/r/ruby/comments/7y2v8u/how_does_rubysinatrabrowsers_readstore_jwts/

https://auth0.com/blog/critical-vulnerabilities-in-json-web-token-libraries/

**Comment by nickdufresne** [comment]
This has been updated to work with the current version of jwt.  Thanks.
